# Generated by Django 2.0.3 on 2018-03-28 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronomic', models.CharField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Краснодарский Край'), (2, 'Ростовская Область'), (3, 'Ставропольский Край')], default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Краснодар'), (2, 'Кропоткин'), (3, 'Славянск'), (4, 'Ростов'), (5, 'Шахты'), (6, 'Батайск'), (7, 'Ставрополь'), (8, 'Пятигорск'), (9, 'Кисловодск')], default=1, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.Region'),
        ),
        migrations.AddField(
            model_name='comment',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.Town'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
